header:
  language:
    Dart:
      extensions:
        - ".dart"
      comment_style_id: SlashAsterisk
    Rust:
      extensions:
        - ".rs"
      comment_style_id: SlashAsterisk
  license:
    spdx-id: "GPL-3.0-or-later"
    copyright-owner: Canonical Ltd
    software-name: gadgets
    content: |
      Copyright (C) 2022 Canonical Ltd

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.

      You should have received a copy of the GNU General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.

  paths-ignore:
    - "bin"
    - "build"
    - "LICENSE"
    - "NOTICE"
    - "linux"
    - "web"
    - "macos"
    - "windows"
    - "venv"
    - "**/pubspec.*"
    - "**/Cargo.*"
    - "**/*/test/fixture"
    - "**/*.html"
    - "**/*.md"
    - "**/*.txt"
    - "**/*.json"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.desktop"
    - "**/.gitignore"
    - "**/.metadata"
    - "**/.dart_tool"
    - "detarball/dart/.dart_tool"
    - "device-tree-lib/.dart_tool"
    - "device-tree-lib/test/fixture"
    - "detarball/rust/target"
    - "**/*.g.dart" # TODO: Remove from version control and add to .gitignore
    - "**/*.freezed.dart" # TODO: Remove from version control and add to .gitignore
    - "**/generated_*.dart" # TODO: Remove from version control and add to .gitignore
    - "**/*_generated.dart" # TODO: Remove from version control and add to .gitignore
    - "**/*_generated.h"
    - "**/*_generated.rs"
  
  comment: on-failure
