name: device_tree_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter_svg: ^1.1.1
  flutter:
    sdk: flutter
  unicons: ^2.1.0
  tuple: ^2.0.0
  flutter_fancy_tree_view:
    git:
      url: https://github.com/mz2/flutter_tree_view.git
      ref: dynamic-item-height
  json_serializable: ^6.3.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  collection: ^1.16.0
  path: ^1.8.1
  dio: ^4.0.6
  riverpod: ^2.0.0-dev.9
  archive: ^3.3.1
  crypto: ^3.0.2
  detarball:
    path: ../detarball/dart

dev_dependencies:
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.16.0
