name: device_tree_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter_fancy_tree_view:
    git:
      url: git@github.com:mz2/flutter_tree_view.git
      ref: dynamic-item-height

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
