name: detarball
description: Dart bindings for a .tar.xz decompressor
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rust_bridge: ^1.38.1
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
