name: gadgets
version: 0.1.0
summary: Inspect your gadgets
description: A tool for inspecting hardware and OS components available on your system.

confinement: strict
base: core18
grade: stable

slots:
  dbus-gadgets:
    interface: dbus
    bus: session
    name: com.canonical.gadgets

apps:
  gadgets:
    command: gadgets
    extensions: [flutter-master]
    plugs:
      - network
    slots:
      - dbus-gadgets
parts:
  gadgets:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages:
      - inxi
