name: gadgets
version: 0.1.0
summary: Inspect your gadgets
description: A tool for inspecting hardware and OS components available on your system.

confinement: strict
base: core18
grade: stable

slots:
  dbus-gadgets:
    interface: dbus
    bus: session
    name: com.canonical.gadgets

apps:
  gadgets:
    command: gadgets
    extensions: [flutter-stable]
    plugs:
      - hardware-observe
      - network
    slots:
      - dbus-gadgets
parts:
  gadgets:
    override-build: |
      dart pub global activate ffigen
      snapcraftctl build
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    flutter-revision: 3.0.5
    build-packages:
      - cargo
      - llvm
    stage-packages:
      - inxi
